site_name: My MKDocs

nav:
- Home: 'index.md'
- User Guide:
    - 'Writing your docs': 'writing-your-docs.md'
    - 'Styling your docs': 'styling-your-docs.md'
- About:
    - 'License': 'about.md'
    - 'Release Notes': 'release-notes.md'

theme: readthedocs # mkdocs